//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public int courseid { get; set; }
        public string course_name { get; set; }
        public Nullable<int> teacher { get; set; }
    
        public virtual teacher teacher1 { get; set; }
    }
}
